app: gimlet-sample-app
env: prod
namespace: default
chart:
  repository: https://chart.onechart.dev
  name: onechart
  version: 0.41.0
values:
  gitRepository: YoucefGuichi/gimlet-sample-app
  gitSha: '{{ .SHA }}'
  image:
    repository: ghcr.io/youcefguichi/gimlet-sample-app
    tag: '{{ .SHA }}'
  vars:
    COLOR: DeepPink
    COLOR2: DarkOrange
    TITLE: Hello from Gimlet
strategicMergePatches: ""
json6902Patches: []
manifests: ""
